apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiro-bot
  namespace: ibuki-shiro-bot
  labels:
    app: shiro-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiro-bot
  template:
    metadata:
      labels:
        app: shiro-bot
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - >-
              until nc -zvw3 shiro-db 3306; do
                echo "waiting for MySQL";
                sleep 3;
              done
        - name: prisma-migrate
          image: kemar1/shiro-bot:latest
          command:
            - sh
            - -c
            - npx prisma migrate deploy
          envFrom:
            - secretRef:
                name: shiro-bot
            - configMapRef:
                name: shiro-bot-config
      containers:
        - name: bot
          image: kemar1/shiro-bot:latest
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - >-
              npx prisma generate &&
              npx prisma migrate deploy &&
              bun run deploy:commands &&
              bun start
          envFrom:
            - secretRef:
                name: shiro-bot
            - configMapRef:
                name: shiro-bot-config
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
