apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ibuki-mitarashi-bot
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - mysql-statefulset.yaml
  - mysql-service.yaml
  - sealed/env.yaml
