apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shiro-bot
  namespace: argocd
spec:
  destination:
    namespace: ibuki-shiro-bot
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/skyia-jp/Shiro-bot.git
    targetRevision: main
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
